/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.aop;

import java.lang.reflect.Method;

/**
 * 用于匹配被执行织入操作的方法.
 * 该接口定义了两个matches,这两个方法的分界线就是isRuntime()方法: 在对对象具体方法进行拦截时,
 * 可以忽略每次方法执行的时候调用者传入的参数,也可以每次都检查这些方法参数,以强化拦截条件.
 * 比如:
 * 如果只想在[方法前]插入某功能,那方法的参数对于Joinpoint捕捉就是可以忽略的;
 * 而如果想在[方法体中]处理一些参数,那么方法的参数就是在匹配Joinpoint的时候必须要考虑的.
 * (1)对于前一种情况: isRuntime返回false,表示不会考虑具体Joinpoint方法参数,
 * 这种类型的MethodMatcher称之为StaticMethodMatcher.因为无需每次都检查参数,
 * 那么对于同样类型的方法匹配结果,可以在框架内部缓存以提高性能.
 * 对于StaticMethodMatcher(isRuntime返回false),
 * 只有boolean matches(Method method, Class<?> targetClass)方法被执行,
 * 返回的匹配结果将会成为其所属Pointcut的主要依据.
 * (2)当isRuntime返回true时,表明MethodMatcher将会每次都对方法参数进行匹配检查,
 * 这种类型的MethodMatcher称之为DynamicMethodMatcher.因为每次都要检查参数,
 * 所以无法对匹配结果进行缓存,故效率较前者差,最好避免使用(大部分情况前者已可以满足需要).
 * 对于DynamicMethodMatcher(当isRuntime返回true),
 * 且方法boolean matches(Method method, Class<?> targetClass)也返回true,
 * boolean matches(Method method, Class<?> targetClass, Object... args)也会被执行,进行进一步检查.
 * 如果两个参数的matches方法返回false,则不管是StaticMethodMatcher还是DynamicMethodMatcher,
 * 该结果已经是最终的匹配结果,无需执行三个参数的matches方法.
 *
 * Part of a {@link Pointcut}: Checks whether the target method is eligible for advice.
 *
 * <p>A MethodMatcher may be evaluated <b>statically</b> or at <b>runtime</b> (dynamically).
 * Static matching involves method and (possibly) method attributes. Dynamic matching
 * also makes arguments for a particular call available, and any effects of running
 * previous advice applying to the joinpoint.
 *
 * <p>If an implementation returns {@code false} from its {@link #isRuntime()}
 * method, evaluation can be performed statically, and the result will be the same
 * for all invocations of this method, whatever their arguments. This means that
 * if the {@link #isRuntime()} method returns {@code false}, the 3-arg
 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method will never be invoked.
 *
 * <p>If an implementation returns {@code true} from its 2-arg
 * {@link #matches(java.lang.reflect.Method, Class)} method and its {@link #isRuntime()} method
 * returns {@code true}, the 3-arg {@link #matches(java.lang.reflect.Method, Class, Object[])}
 * method will be invoked <i>immediately before each potential execution of the related advice</i>,
 * to decide whether the advice should run. All previous advice, such as earlier interceptors
 * in an interceptor chain, will have run, so any state changes they have produced in
 * parameters or ThreadLocal state will be available at the time of evaluation.
 *
 * <p>Concrete implementations of this interface typically should provide proper
 * implementations of {@link Object#equals(Object)} and {@link Object#hashCode()}
 * in order to allow the matcher to be used in caching scenarios &mdash; for
 * example, in proxies generated by CGLIB.
 *
 * @author Rod Johnson
 * @since 11.11.2003
 * @see Pointcut
 * @see ClassFilter
 */
public interface MethodMatcher {

	/**
	 * Perform static checking whether the given method matches.
	 * <p>If this returns {@code false} or if the {@link #isRuntime()}
	 * method returns {@code false}, no runtime check (i.e. no
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} call)
	 * will be made.
	 * @param method the candidate method
	 * @param targetClass the target class
	 * @return whether or not this method matches statically
	 */
	boolean matches(Method method, Class<?> targetClass);

	/**
	 * Is this MethodMatcher dynamic, that is, must a final call be made on the
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method at
	 * runtime even if the 2-arg matches method returns {@code true}?
	 * <p>Can be invoked when an AOP proxy is created, and need not be invoked
	 * again before each method invocation,
	 * @return whether or not a runtime match via the 3-arg
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method
	 * is required if static matching passed
	 */
	boolean isRuntime();

	/**
	 * Check whether there a runtime (dynamic) match for this method,
	 * which must have matched statically.
	 * <p>This method is invoked only if the 2-arg matches method returns
	 * {@code true} for the given method and target class, and if the
	 * {@link #isRuntime()} method returns {@code true}. Invoked
	 * immediately before potential running of the advice, after any
	 * advice earlier in the advice chain has run.
	 * @param method the candidate method
	 * @param targetClass the target class
	 * @param args arguments to the method
	 * @return whether there's a runtime match
	 * @see MethodMatcher#matches(Method, Class)
	 */
	boolean matches(Method method, Class<?> targetClass, Object... args);


	/**
	 * Canonical instance that matches all methods.
	 */
	MethodMatcher TRUE = TrueMethodMatcher.INSTANCE;

}
